module.exports = (HTMLt) => HTMLt
    .replace(/\n/g, '')
    .replace(/ /g, ' ')
    .replace(/&nbsp;/g, ' ')
    .replace(/&quot;/g, '"')    
    .replace(/<div[^>]*>/ig, '')
    .replace(/<span[^>]*>/ig, '')
    .replace(/<a[^>]*>/ig, '')
    .replace(/<\/div>/ig, '\n')    
    .replace(/<\/span>/ig, '\n')
    .replace(/<\/a>/ig, '')
    // .replace(/<\/\s*(?:p|div)>/ig, '\n')
    .replace(/<br[^>]*\/?>/ig, '\n')
    .replace(/[^\S\r\n][^\S\r\n]+/ig, ' ') // множественные пробелы
    .trim()
